# Generated by Django 4.2.7 on 2026-09-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_excel', models.FileField(blank=True, upload_to='batches/excel/')),
                ('photo_archive', models.FileField(blank=True, upload_to='batches/photos/')),
                ('output_archive', models.FileField(blank=True, upload_to='batches/output/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('generated', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'certificate batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(upload_to='templates/')),
                ('is_default', models.BooleanField(default=False, help_text='The template the editor starts with. Only one may be default.')),
                ('layout_overrides', models.JSONField(blank=True, default=dict, help_text='Optional coordinate tweaks, e.g. {"fields": {"year": {"x": 1120}}}. Leave as {} to use the measured defaults.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.CharField(blank=True, max_length=60, verbose_name='SL. No.')),
                ('student_name', models.CharField(max_length=120)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=60)),
                ('year', models.CharField(blank=True, max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('image', models.ImageField(upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.certificatebatch')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificatebatch',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate'),
        ),
    ]
