# Generated by Django 4.2.7 on 2026-09-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatebatch',
            name='photo_archive',
        ),
    ]
