# Generated by Django 4.2.7 on 2026-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_remove_certificatebatch_photo_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatebatch',
            name='hod_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='hod_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
