# Generated by Django 4.2.7 on 2026-09-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatebatch_hod_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatebatch',
            name='output_format',
            field=models.CharField(default='jpg', max_length=16),
        ),
    ]
